"""Add suggestions table

Revision ID: 02033ba62d78
Revises: ad4757e63be3
Create Date: 2026-03-08 19:34:18.750900

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '02033ba62d78'
down_revision: Union[str, Sequence[str], None] = 'ad4757e63be3'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('suggestions',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('couple_id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('tier', sa.String(), nullable=False),
    sa.Column('message', sa.String(), nullable=False),
    sa.Column('actions', postgresql.ARRAY(sa.String()), nullable=True),
    sa.Column('acted_on', sa.Boolean(), nullable=True),
    sa.Column('acted_on_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('suggestions')
    # ### end Alembic commands ###
