"""Add profile fields

Revision ID: 60bd59de9623
Revises: 02033ba62d78
Create Date: 2026-03-09 01:22:43.446543

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '60bd59de9623'
down_revision: Union[str, Sequence[str], None] = '02033ba62d78'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('mood_logs', 'logged_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=True)
    op.add_column('users', sa.Column('display_name', sa.String(), nullable=True))
    op.add_column('users', sa.Column('age', sa.Integer(), nullable=True))
    op.add_column('users', sa.Column('relationship_type', sa.String(), nullable=True))
    op.add_column('users', sa.Column('together_duration', sa.String(), nullable=True))
    op.add_column('users', sa.Column('anniversary_date', sa.String(), nullable=True))
    op.add_column('users', sa.Column('timezone', sa.String(), nullable=True))
    op.add_column('users', sa.Column('profile_complete', sa.Boolean(), server_default='false', nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'profile_complete')
    op.drop_column('users', 'timezone')
    op.drop_column('users', 'anniversary_date')
    op.drop_column('users', 'together_duration')
    op.drop_column('users', 'relationship_type')
    op.drop_column('users', 'age')
    op.drop_column('users', 'display_name')
    op.alter_column('mood_logs', 'logged_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=False)
    # ### end Alembic commands ###
