"""add_confidence_and_was_helpful_to_nudge

Revision ID: 73487e6e6449
Revises: ceeea1080a3d
Create Date: 2026-03-12 00:34:25.611387

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '73487e6e6449'
down_revision: Union[str, Sequence[str], None] = 'ceeea1080a3d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('partner_nudges', sa.Column('confidence', sa.Float(), nullable=False, server_default='1.0'))
    op.add_column('partner_nudges', sa.Column('was_helpful', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('partner_nudges', 'was_helpful')
    op.drop_column('partner_nudges', 'confidence')
    # ### end Alembic commands ###
