"""add_expo_push_token_to_users

Revision ID: d94c6425d85e
Revises: 73487e6e6449
Create Date: 2026-03-12 00:54:52.065710

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd94c6425d85e'
down_revision: Union[str, Sequence[str], None] = '73487e6e6449'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('expo_push_token', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'expo_push_token')
    # ### end Alembic commands ###
